import FastFact from "@/components/about/FastFact";
import Founder from "@/components/about/Founder";
import OffersCart from "@/components/homepage/OffersCart";
import Testimonial from "@/components/homepage/Testimonial";
import InnerBanner from "@/util/InnerBanner";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "BlueBee || About Us",
  description: "Generated by create BlueBee",
};
function Home() {
  return (
    <>
      <InnerBanner>
        <h2 className="heading1">About Us 👋</h2>
        <p>
        We’re impartial and independent, and every day we create distinctive, <br />world-class programmes and content which inform, educate and entertain <br />millions of people in the around the world.
        </p>
      </InnerBanner>
      <Founder />
      <section className='testimonial border-t-2 bg-gradient-to-tl from-slate-200'>
        <Testimonial />
      </section>
      <FastFact />
      <section className='offer-sec bg-gradient-to-tl from-amber-100'>
        <OffersCart />
      </section>
    </>
  );
}

export default Home;
